name: Notify MS Teams of Leaderboard
on:
  schedule:                                      # run workflow based on schedule
    - cron: '0 4 1-26 12 *'                      # from the 1. December till 25. December every day at 4am
                                                 # be carefull with this setting
                                                 # as the workflow should only be triggered at a rate lower than
                                                 # 4 times an hour to keep traffic on aoc site low

  workflow_dispatch:                             # allow to manually start the workflow

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4                # clones your repo
      - uses: actions/setup-node@v4              # sets up Node
        with:
          node-version: '20'
      - run: npm start
        env:
          AOC_LEADERBOARD_ID: ${{ secrets.AOC_LEADERBOARD_ID }}
          AOC_COOKIE: ${{ secrets.AOC_COOKIE }}
          TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          EVENT_YEAR: ${{ secrets.EVENT_YEAR }}
          LEADERBOARD_NAME: ${{ secrets.LEADERBOARD_NAME }}
          LEADERBOARD_SORT: ${{ secrets.LEADERBOARD_SORT }}
          LEADERBOARD_CODE: ${{ secrets.LEADERBOARD_CODE }}
          LEADERBOARD_DISPLAY_GLOBAL_SCORE: ${{ secrets.LEADERBOARD_DISPLAY_GLOBAL_SCORE }}
          LEADERBOARD_DISPLAY_LOCAL_SCORE: ${{ secrets.LEADERBOARD_DISPLAY_LOCAL_SCORE }}
          LEADERBOARD_LIMIT: ${{ secrets.LEADERBOARD_LIMIT }}
          REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
